#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/share/wol_ws/daemon.lua

start_service() {
	config_load wol_ws
	local enabled
	config_get_bool enabled config enabled 0

	if [ "$enabled" -ne 1 ]; then
		return 1
	fi

	procd_open_instance
	procd_set_param command lua "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wol_ws"
}